name: witch_one
description: "What to eat today?"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # 存储相关
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # 网络相关
  cached_network_image: ^3.3.1

  # 工具包
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

# 资源
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/icons/icon.png
    
  shaders:
    - assets/shaders/ray_trace.frag

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icons/icon.png"

  android: true
  # image_path_android: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"

  ios: true
  # image_path_ios: "assets/icons/icon.png"
  remove_alpha_ios: true


  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/icons/icon.png"
